### PR TITLE
added isDecimal and isDecimal spec

### PR DESCRIPTION
**Pull request by D1esel-Dev**
Non notation check for if the parameters passes are decimals, including spec and all tests passed with 100% coverage.

### CODE REVIEW

**Comment by jhowardjr** [comment]
@D1esel-Dev try running ```npm run fix``` that should fix most lint issues.

**Comment by D1esel-Dev** [comment]
ill get this, my dumb a forgot the spacing with comments

**Comment by jhowardjr** [comment]
I just merged a fix for the linter that should help you see the issues in your IDE. Let me know if that helps.

**Comment by D1esel-Dev** [comment]
Gahh headache.. fix one break another. linter fix helped!

**Comment by jhowardjr** [comment]
Cool! I'm trying to fix some issues people are finding between macos and windows. I think I have the complete fix now. I've published the package with your updates new functions.

**Pull request merged**
