### PR TITLE
add range

### PR DESCRIPTION
**Pull request by tdnelson2**
Returns the difference between the largest and smallest values.

### CODE REVIEW

**Comment by jhowardjr** [comment]
@D1esel-Dev check this out. If you comment out the second ```testMaxMinSafe```  it looks like ```Number.MAX_SAFE_INTEGER < range(Number.MAX_SAFE_INTEGER, Number.MIN_SAFE_INTEGER)``` evaluates to true. Is that what you see?

**Comment by tdnelson2** [comment]
@jhowardjr I was thinking because you could have `params` that look like this: `[9007199254740990, -9007199254740990]`, the result of `high - low` would be `18014398509481980` which would exceed `MAX_SAFE_INTEGER`. I wasn't sure returning a result of this size would cause problems or not. If you know for sure it won't, I'll remove it.

**Comment by jhowardjr** [comment]
@tdnelson2 you are correct. 18014398509481980 isn't a safe integer. Looking at examples of where that becomes a problem I tried the following:

```
    console.log(range(Number.MAX_SAFE_INTEGER ,Number.MIN_SAFE_INTEGER) + 1  === range(Number.MAX_SAFE_INTEGER ,Number.MIN_SAFE_INTEGER) + 2) // evaluates to true
```

The only way I was able to get this to evaluate correctly was to convert the difference to a float and return the result in scientific notation:

```
 Number.parseFloat(result).toExponential()
```

I think to throw an error as you do will suffice for now and maybe think about the best way to return larger values. Another interesting thing I found: 

```
Number.isSafeInteger
```

**Comment by tdnelson2** [comment]
I agree. I also think it would be best to refactor some of the most common methods into a separate more comprehensive module since a lot of the modules have very similar error handling methods.

**Pull request merged**
